#baseurl = "https://dev-kr.nl/preview/kees-online/public"
baseurl = "https://kees.online"
title = "kees.online"
canonifyurls = true
paginate = 10
theme = "startbootstrap-clean-blog"
languageCode = "en-us"
copyright = "Code released under the Apache 2.0 license."

[author]
    name = "Benoît Benedetti"

[params]
  DateForm = "Mon, Jan 2, 2006"
  Description = "Getting more out of life thanks to technology"
  Author = "Kees Reusen"
  email = "me@kees.online"
  Ganalytics = "XX-00000000-0"

[[params.social]]
    title = "twitter"
    url = "https://twitter.com/humboldtux"
[[params.social]]
    title = "github"
    url = "https://github.com/humboldtux"
[[params.social]]
    title = "facebook"
    url = "https://www.facebook.com/FACEBOOKHANDLE"

[[menu.main]]
  name = "home"
  url = "/"
  weight = -200
[[menu.main]]
  name = "Archives"
  url = "/post/"
  weight = -180
