#baseurl = "https://dev-kr.nl/preview/kees-online/public"
baseurl = "https://kees.online"
title = "kees.online"
canonifyurls = true
paginate = 10
theme = "startbootstrap-clean-blog"
languageCode = "en-us"
DisqusShortname = "kees-online"

[author]
    name = "Kees Reusen"

[params]
  DateForm = "Mon, Jan 2, 2006"
  Description = "Getting more out of life thanks to technology"
  Author = "Kees Reusen"
  email = "me@kees.online"
  Ganalytics = "UA-93281004-1"

[[params.social]]
    title = "envelope"
    url = "/about"
[[params.social]]
    title = "linkedin"
    url = "https://www.linkedin.com/in/keesreusen/"
[[params.social]]
    title = "github"
    url = "https://github.com/KReusen"

[[menu.main]]
  name = "home"
  url = "/"
  weight = -200

[params.footer]
  footerlinktext = "Humboldtux"
  footerlink = "https://github.com/humboldtux/startbootstrap-clean-blog"